[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则


;设置规则标志位
ruleset=🎯全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
;ruleset=🛑广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;ruleset=🍃应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;ruleset=🆎AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
;ruleset=🆎AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🧠OpenAi,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=📢谷歌服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=📢谷歌服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎮游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🎮游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Xbox.list
ruleset=🕹Steam,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/Steam_CDN.list
ruleset=📟️Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Telegram.list
ruleset=🐦Twitter,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitter.list
ruleset=📚Pixiv,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Pixiv.list
ruleset=🕮EH,https://raw.githubusercontent.com/Kilge/OpenClash/main/Clash/EH.list
ruleset=📱Discord,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Discord.list
ruleset=🤖Reddit,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Reddit.list
ruleset=📖Wikipedia,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Wikipedia.list
ruleset=📕UAA,https://raw.githubusercontent.com/Kilge/OpenClash/main/Clash/UAA.list
ruleset=📹YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📹YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list
ruleset=🎥Twitch,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitch.list
ruleset=🌐Github,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=📺巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=Ⓜ️微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🔞Pornweb,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Porn.list
ruleset=🚀节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🎯全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=🎯全球直连,[]GEOIP,LAN
;ruleset=🎯全球直连,[]GEOIP,CN
ruleset=🐟漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=♻️自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🚀手动切换`select`.*
custom_proxy_group=🚀节点选择`select`[]DIRECT`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=📢谷歌服务`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=Ⓜ️微软云盘`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=Ⓜ️微软服务`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=📺巴哈姆特`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🚀手动切换
custom_proxy_group=📺哔哩哔哩`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🚀手动切换
custom_proxy_group=🎮游戏平台`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=🕹Steam`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=📟️Telegram`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=🐦Twitter`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=📚Pixiv`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=🕮EH`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=🤖Reddit`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=📖Wikipedia`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=📕UAA`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=📱Discord`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=📹YouTube`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=🎥Twitch`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=🔞Pornweb`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=🌐Github`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=🧠OpenAi`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=🐟漏网之鱼`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择`[]🇨🇳台湾节点`[]🇭🇰香港节点`[]🇲🇴澳门节点`[]🇸🇬狮城节点`[]🇯🇵日本节点`[]🇺🇲美国节点`[]🇰🇷韩国节点`[]🇦🇺澳洲节点`[]🇩🇪德国节点`[]🇻🇳越南节点`[]🇹🇷土鸡节点`[]🇮🇳印度节点`[]🇹🇭泰国节点`[]🇷🇺俄国节点`[]🇲🇾马来节点`[]🇸🇪瑞典节点`[]🇪🇬埃及节点`[]🇳🇴挪威节点`[]🇵🇹葡国节点`[]🇦🇶南极节点`[]🇦🇷阿区节点`[]🚀手动切换
custom_proxy_group=🎯全球直连`select`[]DIRECT`[]🚀节点选择`[]♻️自动选择
custom_proxy_group=🛑广告拦截`select`[]REJECT`[]DIRECT
;custom_proxy_group=🍃应用净化`select`[]REJECT`[]DIRECT
;custom_proxy_group=🆎AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🇨🇳台湾节点`url-test`(台湾|台北|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰香港节点`url-test`(香港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇲🇴澳门节点`url-test`(澳门|MO|Macao|Macau)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵日本节点`url-test`(日本|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲美国节点`url-test`(美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇰🇷韩国节点`url-test`(KR|Korea|KOR|首尔|韩国|韓)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇦🇺澳洲节点`url-test`(澳洲|澳大利亚|Australia|AU)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇩🇪德国节点`url-test`(德国|德意志|DE|Germany|GER)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇻🇳越南节点`url-test`(越南|VN|Vietnam)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇷土鸡节点`url-test`(土耳其|土鸡|TR|Turkey|Türkiye)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇮🇳印度节点`url-test`(印度|IN|IND|India)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇭泰国节点`url-test`(泰国|TH|THA|Thailand)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇷🇺俄国节点`url-test`(俄罗斯|RU|RUS|Russia)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇲🇾马来节点`url-test`(马来西亚|马来|大马|MY|MYS|Malaysia)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇪瑞典节点`url-test`(瑞典|SWE|SE|Sweden|Sverige)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇪🇬埃及节点`url-test`(埃及|EG|EGY)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇳🇴挪威节点`url-test`(挪威|NO|NOR|Norway)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇵🇹葡国节点`url-test`(葡萄牙|葡国|PT|PRT|Portuguese)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇦🇶南极节点`url-test`(南极洲|南极|AQ|Antarctica)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇦🇷阿区节点`url-test`(阿根廷|阿区|AR|ARG|Argentina)`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
